spring:
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:sdj2024}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:151430}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
